services:
  ironsbot:
    image: ghcr.io/crispww/seerbot:latest
    container_name: ironsbot
    depends_on:
      - napcat
    ports:
      - "8080:8080"
    environment:
      ONEBOT_ACCESS_TOKEN: ${ONEBOT_ACCESS_TOKEN}
      SUPERUSERS: '${SUPERUSERS:-[]}'
      COMMAND_START: '${COMMAND_START:-[""]}'
      SEERAPI_SYNC_URL: ${SEERAPI_SYNC_URL:-https://github.com/SeerAPI/api-data/releases/download/latest/seerapi-data.sqlite}
      ALIAS_SYNC_URL: ${ALIAS_SYNC_URL:-https://github.com/SeerAPI/api-data/releases/download/latest/aliases-data.sqlite}
      SEERAPI_LOCAL_PATH: ${SEERAPI_LOCAL_PATH:-seerapi-data.sqlite}
      ALIAS_LOCAL_PATH: ${ALIAS_LOCAL_PATH:-aliases-data.sqlite}

    restart: always

  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: always
    mac_address: 02:42:ac:11:00:02

    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}

    ports:
      - 6099:6099

    volumes:
      - ./napcat/config:/app/napcat/config
      - ./ntqq:/app/.config/QQ
